name: Update expo
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read JSON file
      id: read_json
      run: |
        var1=$(jq -r '.name' src/data.json)
        var2=$(jq -r '.id' src/data.json)
        echo "::set-output name=var1::$var1"
        echo "::set-output name=var2::$var2"
      shell: bash

    - name: Use variables
      run: |
        echo "Var1 is ${{ steps.read_json.outputs.var1 }}"
        echo "Var2 is ${{ steps.read_json.outputs.var2 }}"
        # Use as variáveis conforme necessário
